# Generated by Django 5.1.3 on 2024-11-27 19:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_order_disponible_remove_order_livre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
